version: "3.4"

services:
  db:
    image: library/postgres:15-alpine
    ports:
      - 5431:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor



volumes:
  saleor-db:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge

